site_name: Express User Documentation
nav:
  - Home: "index.md"
  - Getting Started: "pages/getting-started.md"

repo_url: https://github.com/megankuo/Express-User-Documentation

repo_name: megankuo/Express-User-Documentation

theme:
  name: material

  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate

  icon:
    repo: fontawesome/brands/git-alt

  # 404 page
  static_templates:
    - 404.html

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - toc:
      toc_depth: 3